import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@coop-super-app/tailwind-config/base-styles";
import GlobalDrawer from "@coop-super-app/lib/view/drawer-view";
import GlobalModal from "@coop-super-app/lib/view/modal-view";
// import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalDrawer />
        <GlobalModal />
        {children}
      </body>
    </html>
  );
}
